### ISSUE TITLE
sorry contacting this way

### ISSUE THREAD

**Issue by BreitiDE** [ddollar/stdapp#14]
I use your fork of victron BLE because it supports inverters ... after a while i find out that the shunt integratin does show negative valued ( -0.9A drain) as positive... so even if I take 1A from battery or put 1A in it shows the value positive. I forked your repo but did not find the error ... regards and thank you for looking into it.

**Comment by ddollar** [comment]
Sorry, I'm not sure. My shunt shows correct values.

**Comment by BreitiDE** [comment]
Hmmm, strange ... Victron app shows -0.94 and ha integration 0.94 ... screenshot 

<img width="358" alt="Bildschirmfoto 2024-03-24 um 21 19 24" src="https://github.com/ddollar/stdapp/assets/24428945/b2dba9c3-a299-428a-8508-3617875dc9a3">


MPPT shows external device load also not correct .. it shows 97 and should be 9,7

<img width="358" alt="Bildschirmfoto 2024-03-24 um 21 09 49" src="https://github.com/ddollar/stdapp/assets/24428945/03a324b5-705c-4086-8b4c-467b397afb83">


Any idea where in the code to look ?
